/* ═══ KARMA — Auth ═══ */

function renderAuth(){
  // If no account exists, force signup mode
  if(!S.auth)authMode='signup';
  document.getElementById('auth-card').innerHTML=`<div class="auth-logo"><div class="auth-k">K</div><div class="auth-brand">KARMA</div></div>
  <div class="glass">
    ${authMode==='login'?`
    <div style="text-align:center;margin-bottom:16px"><div style="font-size:15px;font-weight:600;margin-bottom:2px">Welcome back</div><div style="font-size:12px;color:var(--t2)">Login to continue</div></div>
    <div class="f-group"><label class="f-label">Username</label><input class="f-input" id="auth-u" placeholder="Username"></div>
    <div class="f-group"><label class="f-label">Password</label><input class="f-input" id="auth-p" type="password" placeholder="Password" onkeydown="if(event.key==='Enter')doLogin()"></div>
    <button class="btn-p" onclick="doLogin()" style="margin-top:4px">Login</button>
    <div style="text-align:center;margin-top:14px;font-size:12px;color:var(--t2)">
      Want a fresh start? <span style="color:var(--gold);cursor:pointer;font-weight:600" onclick="authMode='signup';renderAuth()">Create new account</span>
    </div>`
    :`
    <div style="text-align:center;margin-bottom:16px"><div style="font-size:15px;font-weight:600;margin-bottom:2px">Create Account</div><div style="font-size:12px;color:var(--t2)">Set up your credentials</div></div>
    <div class="f-group"><label class="f-label">Choose a username</label><input class="f-input" id="auth-u" placeholder="username"></div>
    <div class="f-group"><label class="f-label">Set a password</label><input class="f-input" id="auth-p" type="password" placeholder="password" onkeydown="if(event.key==='Enter')doSignup()"></div>
    <button class="btn-p" onclick="doSignup()" style="margin-top:4px">Create Account</button>
    ${S.auth?`<div style="text-align:center;margin-top:14px;font-size:12px;color:var(--t2)">
      Have an account? <span style="color:var(--gold);cursor:pointer;font-weight:600" onclick="authMode='login';renderAuth()">Login instead</span>
    </div>`:''}`}
  </div>`;
}

function doLogin(){const u=document.getElementById('auth-u').value.trim(),p=document.getElementById('auth-p').value;if(!S.auth){showToast('No account found — create one first');authMode='signup';renderAuth();return}if(u===S.auth.username&&p===S.auth.password){showScreen('scr-app');goTo('dashboard')}else{showToast('Wrong credentials')}}

function doSignup(){const u=document.getElementById('auth-u').value.trim(),p=document.getElementById('auth-p').value;if(!u||!p){showToast('Fill both fields');return}
  // If creating a new account when one exists, reset all data
  if(S.auth){if(!confirm('This will erase all existing data and create a fresh account. Continue?'))return;
    S={auth:null,profile:{onboarding_complete:false},player:{level:1,xp:0,hp:100,gold:0,pending:0,stats:{str:5,con:5,int:5,per:5},statXP:{str:0,con:0,int:0,per:0},statLevels:{str:1,con:1,int:1,per:1}},habits:JSON.parse(JSON.stringify(DEF_HABITS)),dailyLog:{},mealLog:{},mealFreq:{},weightLog:{},waterLog:{},todos:[],expenses:[],expenseCats:['Food','Transport','Shopping','Health','Entertainment','Bills','Other'],customMeals:[],hiddenMeals:[],budget:{monthly:0},lentMoney:[],achievements:[],lastCron:null,workoutProgram:JSON.parse(JSON.stringify(DEF_PROGRAM)),workoutLog:{},activityLog:{}}}
  S.auth={username:u,password:p};save();showScreen('scr-onboard');renderOnboarding()}

function renderOnboarding(){renderOnbStep()}

function renderOnbStep(){
  const card=document.getElementById('onb-card');const total=5;
  const dots=`<div class="steps-bar">${Array.from({length:total},(_,i)=>`<div class="step-d ${i<onbStep?'done':i===onbStep?'cur':''}"></div>`).join('')}</div>`;
  let h='';
  switch(onbStep){
    case 0:h=`<div class="auth-logo"><div class="auth-k">K</div></div><div class="glass">${dots}<div style="text-align:center;margin-bottom:14px"><div style="font-size:14px;font-weight:600;margin-bottom:2px">Your profile</div><div style="font-size:11px;color:var(--t2)">Tell us who you are</div></div><div class="f-group"><label class="f-label">Name</label><input class="f-input" id="inp-n" value="${OD.name}" placeholder="Your name"></div><div class="f-row"><div class="f-group"><label class="f-label">Date of birth</label><input class="f-input" id="inp-dob" type="date" value="${OD.dob}"></div><div class="f-group"><label class="f-label">Gender</label><div class="chip-grid">${['Male','Female','Other'].map(g=>`<div class="chip ${OD.gender===g.toLowerCase()?'sel':''}" onclick="selC(this,'gender','${g.toLowerCase()}')">${g}</div>`).join('')}</div></div></div><div class="f-group"><label class="f-label">Height (cm)</label><input class="f-input" id="inp-h" type="number" placeholder="187" value="${OD.height}" style="width:100px"></div><button class="btn-p" onclick="nextOnb()">Continue</button></div>`;break;
    case 1:h=`<div class="auth-logo"><div class="auth-k">K</div></div><div class="glass">${dots}<div style="font-size:14px;font-weight:600;margin-bottom:2px">What's your mission?</div><div style="font-size:11px;color:var(--t2);margin-bottom:14px">Select all goals</div><div class="goal-grid">${[{id:'fat_loss',ico:'🔥',name:'Fat Loss',desc:'Get lean'},{id:'muscle_gain',ico:'💪',name:'Muscle',desc:'Build mass'},{id:'visible_abs',ico:'🎯',name:'Abs',desc:'Sub-15% BF'},{id:'strength',ico:'🏋️',name:'Strength',desc:'Lift heavy'},{id:'endurance',ico:'🏃',name:'Endurance',desc:'Cardio'},{id:'mental',ico:'🧠',name:'Mental',desc:'Discipline'},{id:'grooming',ico:'✨',name:'Grooming',desc:'Look good'},{id:'flexibility',ico:'🧘',name:'Flexibility',desc:'Mobility'}].map(g=>`<div class="goal-card ${OD.goals.includes(g.id)?'sel':''}" onclick="toggleGoal(this,'${g.id}')"><div class="gc-ico">${g.ico}</div><div class="gc-name">${g.name}</div><div class="gc-desc">${g.desc}</div></div>`).join('')}</div><div style="display:flex;gap:6px;margin-top:12px"><button class="btn-g" onclick="prevOnb()">Back</button><button class="btn-p" onclick="nextOnb()">Continue</button></div></div>`;break;
    case 2:const sug=calcSug();h=`<div class="auth-logo"><div class="auth-k">K</div></div><div class="glass">${dots}<div style="font-size:14px;font-weight:600;margin-bottom:2px">Body & Diet</div><div style="font-size:11px;color:var(--t2);margin-bottom:14px">Target based on your goals</div><div class="f-row"><div class="f-group"><label class="f-label">Current weight (kg)</label><input class="f-input" id="inp-w" type="number" placeholder="98" value="${OD.weight}" oninput="updateSug()"></div><div class="f-group"><label class="f-label">Target weight (kg)</label><input class="f-input" id="inp-tw" type="number" placeholder="${sug}" value="${OD.target_weight}"></div></div><div class="target-sug"><div style="font-size:14px">🎯</div><div style="flex:1;font-size:10px;color:var(--t2)">Recommended for your goals:</div><div class="ts-v" id="ts-v">${sug} kg</div><button class="ts-use" onclick="useSug()">Use</button></div><div class="f-group" style="margin-top:10px"><label class="f-label">Diet</label><div class="chip-grid">${['Vegetarian','Non-veg','Eggetarian','Vegan'].map(d=>`<div class="chip ${OD.diet===d?'sel':''}" onclick="selC(this,'diet','${d}')">${d}</div>`).join('')}</div></div><div class="f-group"><label class="f-label">Injuries</label><div class="chip-grid">${['Knee','Ankle','Back','Shoulder','None'].map(i=>`<div class="chip ${OD.injuries.includes(i)?'sel':''}" onclick="toggleMC(this,'injuries','${i}')">${i}</div>`).join('')}</div></div><div style="display:flex;gap:6px;margin-top:8px"><button class="btn-g" onclick="prevOnb()">Back</button><button class="btn-p" onclick="nextOnb()">Continue</button></div></div>`;break;
    case 3:h=`<div class="auth-logo"><div class="auth-k">K</div></div><div class="glass">${dots}<div style="font-size:14px;font-weight:600;margin-bottom:2px">Routine</div><div style="font-size:11px;color:var(--t2);margin-bottom:14px">Schedule & experience</div><div class="f-group"><label class="f-label">Experience</label><div class="chip-grid">${[['Beginner','<1yr'],['Intermediate','1-3yr'],['Advanced','3+yr']].map(([n,d])=>`<div class="chip ${OD.experience===n.toLowerCase()?'sel':''}" onclick="selC(this,'experience','${n.toLowerCase()}')">${n} <span style="color:var(--t3);font-size:9px;margin-left:2px">${d}</span></div>`).join('')}</div></div><div class="f-group"><label class="f-label">Workout time</label><div class="chip-grid">${['Early morning','Morning','Afternoon','Evening'].map(t=>`<div class="chip ${OD.workout_time===t?'sel':''}" onclick="selC(this,'workout_time','${t}')">${t}</div>`).join('')}</div></div><div class="f-row"><div class="f-group"><label class="f-label">Wake</label><input class="f-input" id="inp-wake" type="time" value="${OD.wake}"></div><div class="f-group"><label class="f-label">Sleep</label><input class="f-input" id="inp-sleep" type="time" value="${OD.sleep}"></div></div><div class="f-group"><label class="f-label">Work</label><div class="chip-grid">${['9-5 Office','Shifts','Flexible','Student','Freelance'].map(w=>`<div class="chip ${OD.work===w?'sel':''}" onclick="selC(this,'work','${w}')">${w}</div>`).join('')}</div></div><div style="display:flex;gap:6px;margin-top:8px"><button class="btn-g" onclick="prevOnb()">Back</button><button class="btn-p" onclick="nextOnb()">Continue</button></div></div>`;break;
    case 4:h=`<div class="auth-logo"><div class="auth-k">K</div></div><div class="glass">${dots}<div style="font-size:14px;font-weight:600;margin-bottom:12px">Review</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:6px;font-size:11px;margin-bottom:12px">${[['Name',OD.name],['Height',OD.height+'cm'],['Weight',OD.weight+'→'+OD.target_weight+'kg'],['Experience',OD.experience],['Diet',OD.diet],['Schedule',OD.work]].map(([k,v])=>`<div style="background:var(--s3);border:1px solid var(--bd);border-radius:6px;padding:8px 10px"><div style="font-size:8px;font-weight:600;letter-spacing:.06em;text-transform:uppercase;color:var(--t4);margin-bottom:1px">${k}</div><div style="font-weight:500">${v||'—'}</div></div>`).join('')}</div><div style="display:flex;gap:6px"><button class="btn-g" onclick="prevOnb()">Back</button><button class="btn-p" onclick="submitProfile()">Launch KARMA</button></div></div>`;break;
  }
  card.innerHTML=h;card.style.animation='none';void card.offsetWidth;card.style.animation='fadeUp .35s var(--ease) both';
}

function nextOnb(){if(onbStep===0){OD.name=document.getElementById('inp-n').value.trim();OD.dob=document.getElementById('inp-dob').value;OD.height=document.getElementById('inp-h').value;if(!OD.name){showToast('Enter name');return}if(!OD.dob){showToast('Enter DOB');return}}if(onbStep===1&&!OD.goals.length){showToast('Select a goal');return}if(onbStep===2){OD.weight=document.getElementById('inp-w').value;OD.target_weight=document.getElementById('inp-tw').value;if(!OD.weight){showToast('Enter weight');return}}if(onbStep===3){OD.wake=document.getElementById('inp-wake')?.value||'06:00';OD.sleep=document.getElementById('inp-sleep')?.value||'22:30';if(!OD.experience){showToast('Select experience');return}}onbStep++;if(onbStep>4)return;renderOnbStep()}

function prevOnb(){if(onbStep>0){onbStep--;renderOnbStep()}}

function submitProfile(){const z=getZodiac(OD.dob);S.profile={name:OD.name,age:Math.floor((Date.now()-new Date(OD.dob))/31557600000),gender:OD.gender,height_cm:parseInt(OD.height),weight_kg:parseFloat(OD.weight),target_weight_kg:parseFloat(OD.target_weight),dob:OD.dob,zodiac:z.s,zodiacIcon:z.i,experience_level:OD.experience,workout_time:OD.workout_time,diet_preference:OD.diet,injuries:OD.injuries,goals:OD.goals,primary_goal:OD.primary_goal,wake_time:OD.wake,sleep_time:OD.sleep,work_schedule:OD.work,created_at:new Date().toISOString(),onboarding_complete:true};if(OD.experience==='advanced')S.player.stats={str:8,con:7,int:5,per:5};else if(OD.experience==='intermediate')S.player.stats={str:6,con:6,int:5,per:5};S.player.hp=maxHP();S.weightLog[todayKey()]=parseFloat(OD.weight);save();runAnalysis()}

function runAnalysis(){showScreen('scr-analysis');const steps=['Calculating body composition','Analyzing training history','Building nutrition profile','Generating tasks','Calibrating stats','Designing habits','Finalizing plan'];document.getElementById('analysis-c').innerHTML=`<div class="a-orb"><div class="a-ring"></div><div class="a-ring"></div><div class="a-core">K</div></div><div class="a-title">Crafting Your Plan</div><div class="a-step-text" id="as-t">${steps[0]}</div><div class="a-steps">${steps.map((s,i)=>`<div class="a-st" id="as-${i}"><div class="a-dot" id="ad-${i}">${i+1}</div><span>${s}</span></div>`).join('')}</div>`;let idx=0;const iv=setInterval(()=>{if(idx>0){document.getElementById('as-'+(idx-1)).classList.remove('active');document.getElementById('as-'+(idx-1)).classList.add('done');document.getElementById('ad-'+(idx-1)).innerHTML='✓'}if(idx<steps.length){document.getElementById('as-'+idx).classList.add('active');document.getElementById('as-t').textContent=steps[idx];idx++}else{clearInterval(iv);setTimeout(()=>{showScreen('scr-app');goTo('dashboard')},600)}},550)}

function selC(el,k,v){OD[k]=v;el.parentElement.querySelectorAll('.chip').forEach(c=>c.classList.remove('sel'));el.classList.add('sel')}

function toggleGoal(el,id){const i=OD.goals.indexOf(id);if(i>=0){OD.goals.splice(i,1);if(OD.primary_goal===id)OD.primary_goal=OD.goals[0]||''}else{OD.goals.push(id);if(!OD.primary_goal)OD.primary_goal=id}renderOnbStep()}

function addSugHabit(name,stat){S.habits.push({id:'s_'+Date.now(),name,cat:stat==='str'?'physical':stat==='con'?'nutrition':stat==='int'?'mental':'grooming',icon:'⭐',stat,base:8,reps:0,streak:0,neg:false});save();renderStatPage(stat);showToast(`${name} added!`)}

function calcSug(){const h=parseInt(OD.height)||180,w=parseInt(OD.weight)||90,g=OD.goals;let bmi=22.5;if(g.includes('visible_abs')||g.includes('fat_loss'))bmi=22;if(g.includes('muscle_gain'))bmi=23.5;let t=Math.round(bmi*(h/100)**2);if((g.includes('fat_loss')||g.includes('visible_abs'))&&t>=w)t=Math.round(w*.88);return Math.max(50,Math.min(150,t))}

function updateSug(){OD.weight=document.getElementById('inp-w').value;const el=document.getElementById('ts-v');if(el)el.textContent=calcSug()+' kg'}

function useSug(){document.getElementById('inp-tw').value=calcSug();OD.target_weight=calcSug().toString()}

function toggleMC(el,k,v){if(!OD[k])OD[k]=[];if(v==='None'){OD[k]=['None']}else{OD[k]=OD[k].filter(x=>x!=='None');const i=OD[k].indexOf(v);if(i>=0)OD[k].splice(i,1);else OD[k].push(v)}el.parentElement.querySelectorAll('.chip').forEach(c=>c.classList.toggle('sel',OD[k].includes(c.textContent.trim())))}

function logout(){document.getElementById('sidebar').classList.remove('open');authMode='login';setTimeout(()=>{showScreen('scr-auth');renderAuth()},100)}
